services:
  mongodb:
    image: mongo:latest
    container_name: celestial_wordforge_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: celestial_wordforge
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongodb_data:
    name: celestial_wordforge_mongodb_data
